version: 2

sources:
  - name: bq_init
    database: linen-sunbeam-368317
    schema: 5r_project
    tables:
      - name: ga_campaigns
        identifier: by_campaigns_b
      - name: fb_ads
        identifier: facebook_ads
      - name: google_ads
        identifier: by_google_ads
  - name: inputs_sheets
    database: linen-sunbeam-368317
    schema: excel_data
    tables:
      - name: manual_inputs
        identifier: inputs_for_manual_metrics
      - name: bi_mappings
        identifier: mapping_sh
      - name: ga_mappings
        identifier: campaign_mapping