version: 2

sources:
  - name: bq_init
    database: linen-sunbeam-368317
    schema: 5r_project
    tables:
      - name: ga_campaigns
        identifier: by_campaigns_b
      - name: fb_ads
        identifier: facebook_ads
      - name: google_ads
        identifier: by_google_ads